# Generated by Django 4.1.6 on 2023-06-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0014_alter_application_arrival_alter_application_day_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
